name: Github Data Extractopr

on:
  workflow_dispatch:  # manual execution
    inputs:
      repositorio:
        description: 'Repository Name (let empty for all repos)'
        required: false
        default: ''
      extracao_global: 
        description: 'Extract global data?'
        required: true
        type: boolean
        default: false
      txt2tsv:
        description: 'Converts .txt to .tsv?'
        required: true
        type: boolean
        default: true
      debug:
        description: 'Debug?'
        required: true
        type: boolean
        default: false

jobs:
  extract:
    runs-on: ${{ vars.VAR_GITHUB_AGENT }}

    env:
      DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_STEP_DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_RUNNER_HTTPTRACE: ${{ github.event.inputs.debug }}
      TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.SEC_GITHUB_TOKEN }}
      REPOSITORIO: ${{ github.event.inputs.repositorio }}
      EXTRACAO_GLOBAL: ${{ github.event.inputs.extracao_global }}
      TXT2TSV: ${{ github.event.inputs.txt2tsv }}
      GITHUB_AGENT: ${{ vars.VAR_GITHUB_AGENT }}

    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      
    - name: Show environment variables
      if: success()
      run: |
        for var in $(compgen -e); do
          echo $var=${!var};
        done
        
    - name: Extract
      run: chmod +x ./extract.sh && ./extract.sh

    - name: Upload files .txt and .tsv
      uses: actions/upload-artifact@v4
      with:
        name: files
        path: |
          *.txt
          *.tsv
